---
- name: DELETE SUBNET | Deleting VLAN {{ vlan_id }}
  uri:
    url: "https://{{ prism_central }}:9440/api/nutanix/v3/subnets/{{ vlan_uuid }}"
    method: DELETE
    validate_certs: no
    force_basic_auth: yes
    headers:
      cookie: "{{ session_cookie }}"
    status_code: 202
    return_content: yes
  register: delete_subnet_info
  ignore_errors: yes

- name: DELETE SUBNET | Debug Subnet Information
  debug:
    var: delete_subnet_info
  when: global_debug

- name: DELETE SUBNET | Saving Task UUID
  set_fact:
    task_uuid: "{{ delete_subnet_info.json.status.execution_context.task_uuid }}"

- name: DELETE SUBNET | Task UUID
  debug:
    var: task_uuid

- name: DELETE SUBNET | Setting Task Name
  set_fact:
    task_name: "delete subnet"

- name: DELETE SUBNET | Task Name
  debug:
    var: task_name
